name: Deploy static site to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm

      - run: npm ci
      - run: npm run build

      # SPA fallback: tránh 404 khi refresh ở đường dẫn con
      - run: cp dist/index.html dist/404.html

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
      - id: deployment
        uses: actions/deploy-pages@v4
